items:
- uid: System.Security
  id: System.Security
  children:
  - System.Security.AllowPartiallyTrustedCallersAttribute
  - System.Security.SecurityCriticalAttribute
  - System.Security.SecurityException
  - System.Security.SecuritySafeCriticalAttribute
  - System.Security.SecurityTransparentAttribute
  - System.Security.VerificationException
  href: System.Security.yml
  name: System.Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      path: src/mscorlib/src/System/Security/AccessControl/Enums.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    path: src/mscorlib/src/System/Security/AccessControl/Enums.cs
    startLine: 5
  assemblies:
  - System.Runtime
  summary: The @'System.Security' namespace provides the underlying structure of the common language runtime security system, including base classes for permissions.
references:
- uid: System.Security.AllowPartiallyTrustedCallersAttribute
  isExternal: false
  href: System.Security.AllowPartiallyTrustedCallersAttribute.yml
  name: AllowPartiallyTrustedCallersAttribute
  fullName: System.Security.AllowPartiallyTrustedCallersAttribute
  type: Class
  summary: Allows an assembly to be called by partially trusted code. Without this declaration, only fully trusted callers are able to use the assembly. This class cannot be inherited.
- uid: System.Security.SecurityCriticalAttribute
  isExternal: false
  href: System.Security.SecurityCriticalAttribute.yml
  name: SecurityCriticalAttribute
  fullName: System.Security.SecurityCriticalAttribute
  type: Class
  summary: Specifies that code or an assembly performs security-critical operations.
- uid: System.Security.SecurityException
  isExternal: false
  href: System.Security.SecurityException.yml
  name: SecurityException
  fullName: System.Security.SecurityException
  type: Class
  summary: The exception that is thrown when a security error is detected.
- uid: System.Security.SecuritySafeCriticalAttribute
  isExternal: false
  href: System.Security.SecuritySafeCriticalAttribute.yml
  name: SecuritySafeCriticalAttribute
  fullName: System.Security.SecuritySafeCriticalAttribute
  type: Class
  summary: Identifies types or members as security-critical and safely accessible by transparent code.
- uid: System.Security.SecurityTransparentAttribute
  isExternal: false
  href: System.Security.SecurityTransparentAttribute.yml
  name: SecurityTransparentAttribute
  fullName: System.Security.SecurityTransparentAttribute
  type: Class
  summary: Specifies that an assembly cannot cause an elevation of privilege.
- uid: System.Security.VerificationException
  isExternal: false
  href: System.Security.VerificationException.yml
  name: VerificationException
  fullName: System.Security.VerificationException
  type: Class
  summary: The exception that is thrown when the security policy requires code to be type safe and the verification process is unable to verify that the code is type safe.
