items:
- uid: System.Net.Security
  id: System.Net.Security
  children:
  - System.Net.Security.AuthenticatedStream
  - System.Net.Security.AuthenticationLevel
  - System.Net.Security.EncryptionPolicy
  - System.Net.Security.LocalCertificateSelectionCallback
  - System.Net.Security.NegotiateStream
  - System.Net.Security.ProtectionLevel
  - System.Net.Security.RemoteCertificateValidationCallback
  - System.Net.Security.SslPolicyErrors
  - System.Net.Security.SslStream
  href: System.Net.Security.yml
  name: System.Net.Security
  fullName: System.Net.Security
  type: Namespace
  source:
    remote:
      path: src/Common/src/Interop/Windows/sspicli/SecuritySafeHandles.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/Common/src/Interop/Windows/sspicli/SecuritySafeHandles.cs
    startLine: 9
  assemblies:
  - System.Net.Primitives
  summary: The @'System.Net.Security' namespace provides network streams for secure communications between hosts.
references:
- uid: System.Net.Security.AuthenticationLevel
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.AuthenticationLevel.yml
  name: AuthenticationLevel
  fullName: System.Net.Security.AuthenticationLevel
  type: Enum
  summary: Specifies client requirements for authentication and impersonation when using the @'System.Net.WebRequest' class and derived classes to request a resource.
- uid: System.Net.Security.SslPolicyErrors
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.SslPolicyErrors.yml
  name: SslPolicyErrors
  fullName: System.Net.Security.SslPolicyErrors
  type: Enum
  summary: Enumerates Secure Socket Layer (SSL) policy errors.
- uid: System.Net.Security.AuthenticatedStream
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.AuthenticatedStream.yml
  name: AuthenticatedStream
  fullName: System.Net.Security.AuthenticatedStream
  type: Class
  summary: Provides methods for passing credentials across a stream and requesting or performing authentication for client-server applications.
- uid: System.Net.Security.EncryptionPolicy
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.EncryptionPolicy.yml
  name: EncryptionPolicy
  fullName: System.Net.Security.EncryptionPolicy
  type: Enum
  summary: The EncryptionPolicy to use.
- uid: System.Net.Security.LocalCertificateSelectionCallback
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.LocalCertificateSelectionCallback.yml
  name: LocalCertificateSelectionCallback
  fullName: System.Net.Security.LocalCertificateSelectionCallback
  type: Delegate
  summary: Selects the local Secure Sockets Layer (SSL) certificate used for authentication.
- uid: System.Net.Security.NegotiateStream
  isExternal: false
  href: System.Net.Security.NegotiateStream.yml
  name: NegotiateStream
  fullName: System.Net.Security.NegotiateStream
  type: Class
  summary: Provides a stream that uses the Negotiate security protocol to authenticate the client, and optionally the server, in client-server communication.
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.ProtectionLevel.yml
  name: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
  type: Enum
  summary: Indicates the security services requested for an authenticated stream.
- uid: System.Net.Security.RemoteCertificateValidationCallback
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.RemoteCertificateValidationCallback.yml
  name: RemoteCertificateValidationCallback
  fullName: System.Net.Security.RemoteCertificateValidationCallback
  type: Delegate
  summary: Verifies the remote Secure Sockets Layer (SSL) certificate used for authentication.
- uid: System.Net.Security.SslStream
  isExternal: false
  href: System.Net.Security.SslStream.yml
  name: SslStream
  fullName: System.Net.Security.SslStream
  type: Class
- uid: System.Net.Security
  isExternal: false
  name: System.Net.Security
  fullName: System.Net.Security
  type: Namespace
