items:
- uid: System.Xml.XmlWriterSettings
  id: XmlWriterSettings
  parent: System.Xml
  children:
  - System.Xml.XmlWriterSettings.#ctor
  - System.Xml.XmlWriterSettings.Async
  - System.Xml.XmlWriterSettings.CheckCharacters
  - System.Xml.XmlWriterSettings.Clone
  - System.Xml.XmlWriterSettings.CloseOutput
  - System.Xml.XmlWriterSettings.ConformanceLevel
  - System.Xml.XmlWriterSettings.Encoding
  - System.Xml.XmlWriterSettings.Indent
  - System.Xml.XmlWriterSettings.IndentChars
  - System.Xml.XmlWriterSettings.NamespaceHandling
  - System.Xml.XmlWriterSettings.NewLineChars
  - System.Xml.XmlWriterSettings.NewLineHandling
  - System.Xml.XmlWriterSettings.NewLineOnAttributes
  - System.Xml.XmlWriterSettings.OmitXmlDeclaration
  - System.Xml.XmlWriterSettings.Reset
  - System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  href: System.Xml.XmlWriterSettings.yml
  name: XmlWriterSettings
  fullName: System.Xml.XmlWriterSettings
  type: Class
  source:
    remote: &o0
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 473
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Specifies a set of features to support on the @'System.Xml.XmlWriter' object created by the <see cref="Overload:System.Xml.XmlWriter.Create" /> method.
  syntax:
    content: 'public sealed class XmlWriterSettings : object'
    content.vb: Public NotInheritable Class XmlWriterSettings Inherits Object
  inheritance:
  - System.Object
- uid: System.Xml.XmlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: XmlWriterSettings()
  fullName: System.Xml.XmlWriterSettings.XmlWriterSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 475
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Initializes a new instance of the @'System.Xml.XmlWriterSettings' class.
  syntax:
    content: public XmlWriterSettings()
    content.vb: Public Sub New
- uid: System.Xml.XmlWriterSettings.Async
  id: Async
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Async
  fullName: System.Xml.XmlWriterSettings.Async
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 476
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value that indicates whether asynchronous @'System.Xml.XmlWriter' methods can be used on a particular @'System.Xml.XmlWriter' instance.
  syntax:
    content: public bool Async { get; set; }
    content.vb: Public Property Async As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: true if asynchronous methods can be used; otherwise, false.
- uid: System.Xml.XmlWriterSettings.CheckCharacters
  id: CheckCharacters
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: CheckCharacters
  fullName: System.Xml.XmlWriterSettings.CheckCharacters
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 477
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value that indicates whether the XML writer should check to ensure that all characters in the document conform to the "2.2 Characters" section of the W3C XML 1.0 Recommendation.
  syntax:
    content: public bool CheckCharacters { get; set; }
    content.vb: Public Property CheckCharacters As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: true to do character checking; otherwise, false. The default is true.
- uid: System.Xml.XmlWriterSettings.CloseOutput
  id: CloseOutput
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: CloseOutput
  fullName: System.Xml.XmlWriterSettings.CloseOutput
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 478
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value indicating whether the @'System.Xml.XmlWriter' should also close the underlying stream or @'System.IO.TextWriter' when the @'System.Xml.XmlWriter.Close' method is called.
  syntax:
    content: public bool CloseOutput { get; set; }
    content.vb: Public Property CloseOutput As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: true to also close the underlying stream or @'System.IO.TextWriter'; otherwise, false. The default is false.
- uid: System.Xml.XmlWriterSettings.ConformanceLevel
  id: ConformanceLevel
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: ConformanceLevel
  fullName: System.Xml.XmlWriterSettings.ConformanceLevel
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 479
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets the level of conformance that the XML writer checks the XML output for.
  syntax:
    content: public ConformanceLevel ConformanceLevel { get; set; }
    content.vb: Public Property ConformanceLevel As ConformanceLevel
    parameters: []
    return:
      type: System.Xml.ConformanceLevel
      description: One of the enumeration values that specifies the level of conformance (document, fragment, or automatic detection). The default is @'System.Xml.ConformanceLevel.Document'.
- uid: System.Xml.XmlWriterSettings.Encoding
  id: Encoding
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Encoding
  fullName: System.Xml.XmlWriterSettings.Encoding
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 480
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets the type of text encoding to use.
  syntax:
    content: public Text.Encoding Encoding { get; set; }
    content.vb: Public Property Encoding As Text.Encoding
    parameters: []
    return:
      type: System.Text.Encoding
      description: The text encoding to use. The default is Encoding.UTF8.
- uid: System.Xml.XmlWriterSettings.Indent
  id: Indent
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Indent
  fullName: System.Xml.XmlWriterSettings.Indent
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 481
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value indicating whether to indent elements.
  syntax:
    content: public bool Indent { get; set; }
    content.vb: Public Property Indent As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: true to write individual elements on new lines and indent; otherwise, false. The default is false.
- uid: System.Xml.XmlWriterSettings.IndentChars
  id: IndentChars
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: IndentChars
  fullName: System.Xml.XmlWriterSettings.IndentChars
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 482
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets the character string to use when indenting. This setting is used when the @'System.Xml.XmlWriterSettings.Indent' property is set to true.
  syntax:
    content: public string IndentChars { get; set; }
    content.vb: Public Property IndentChars As String
    parameters: []
    return:
      type: System.String
      description: The character string to use when indenting. This can be set to any string value. However, to ensure valid XML, you should specify only valid white space characters, such as space characters, tabs, carriage returns, or line feeds. The default is two spaces.
  exceptions:
  - type: System.ArgumentNullException
    description: The value assigned to the @'System.Xml.XmlWriterSettings.IndentChars' is null.
- uid: System.Xml.XmlWriterSettings.NamespaceHandling
  id: NamespaceHandling
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: NamespaceHandling
  fullName: System.Xml.XmlWriterSettings.NamespaceHandling
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 483
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value that indicates whether the @'System.Xml.XmlWriter' should remove duplicate namespace declarations when writing XML content. The default behavior is for the writer to output all namespace declarations that are present in the writer's namespace resolver.
  syntax:
    content: public NamespaceHandling NamespaceHandling { get; set; }
    content.vb: Public Property NamespaceHandling As NamespaceHandling
    parameters: []
    return:
      type: System.Xml.NamespaceHandling
      description: The @'System.Xml.NamespaceHandling' enumeration used to specify whether to remove duplicate namespace declarations in the @'System.Xml.XmlWriter'.
- uid: System.Xml.XmlWriterSettings.NewLineChars
  id: NewLineChars
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineChars
  fullName: System.Xml.XmlWriterSettings.NewLineChars
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 484
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets the character string to use for line breaks.
  syntax:
    content: public string NewLineChars { get; set; }
    content.vb: Public Property NewLineChars As String
    parameters: []
    return:
      type: System.String
      description: The character string to use for line breaks. This can be set to any string value. However, to ensure valid XML, you should specify only valid white space characters, such as space characters, tabs, carriage returns, or line feeds. The default is \r\n (carriage return, new line).
  exceptions:
  - type: System.ArgumentNullException
    description: The value assigned to the @'System.Xml.XmlWriterSettings.NewLineChars' is null.
- uid: System.Xml.XmlWriterSettings.NewLineHandling
  id: NewLineHandling
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineHandling
  fullName: System.Xml.XmlWriterSettings.NewLineHandling
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 485
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value indicating whether to normalize line breaks in the output.
  syntax:
    content: public NewLineHandling NewLineHandling { get; set; }
    content.vb: Public Property NewLineHandling As NewLineHandling
    parameters: []
    return:
      type: System.Xml.NewLineHandling
      description: One of the @'System.Xml.NewLineHandling' values. The default is @'System.Xml.NewLineHandling.Replace'.
- uid: System.Xml.XmlWriterSettings.NewLineOnAttributes
  id: NewLineOnAttributes
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineOnAttributes
  fullName: System.Xml.XmlWriterSettings.NewLineOnAttributes
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 486
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value indicating whether to write attributes on a new line.
  syntax:
    content: public bool NewLineOnAttributes { get; set; }
    content.vb: Public Property NewLineOnAttributes As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: true to write attributes on individual lines; otherwise, false. The default is false.NoteThis setting has no effect when the @'System.Xml.XmlWriterSettings.Indent' property value is false.When @'System.Xml.XmlWriterSettings.NewLineOnAttributes' is set to true, each attribute is pre-pended with a new line and one extra level of indentation.
- uid: System.Xml.XmlWriterSettings.OmitXmlDeclaration
  id: OmitXmlDeclaration
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: OmitXmlDeclaration
  fullName: System.Xml.XmlWriterSettings.OmitXmlDeclaration
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 487
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value indicating whether to omit an XML declaration.
  syntax:
    content: public bool OmitXmlDeclaration { get; set; }
    content.vb: Public Property OmitXmlDeclaration As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: true to omit the XML declaration; otherwise, false. The default is false, an XML declaration is written.
- uid: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  id: WriteEndDocumentOnClose
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: WriteEndDocumentOnClose
  fullName: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 488
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Gets or sets a value that indicates whether the @'System.Xml.XmlWriter' will add closing tags to all unclosed element tags when the @'System.Xml.XmlWriter.Close' method is called.
  syntax:
    content: public bool WriteEndDocumentOnClose { get; set; }
    content.vb: Public Property WriteEndDocumentOnClose As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: true if all unclosed element tags will be closed out; otherwise, false. The default value is true.
- uid: System.Xml.XmlWriterSettings.Clone
  id: Clone
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Clone()
  fullName: System.Xml.XmlWriterSettings.Clone()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 489
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Creates a copy of the @'System.Xml.XmlWriterSettings' instance.
  syntax:
    content: public XmlWriterSettings Clone()
    content.vb: Public Function Clone As XmlWriterSettings
    return:
      type: System.Xml.XmlWriterSettings
      description: The cloned @'System.Xml.XmlWriterSettings' object.
- uid: System.Xml.XmlWriterSettings.Reset
  id: Reset
  parent: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: Reset()
  fullName: System.Xml.XmlWriterSettings.Reset()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 490
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  summary: Resets the members of the settings class to their default values.
  syntax:
    content: public void Reset()
    content.vb: Public Sub Reset
references:
- uid: System.Xml
  isExternal: false
  name: System.Xml
  fullName: System.Xml
- uid: System.Object
  parent: System
  isExternal: false
  href: System.Object.yml
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Boolean
  parent: System
  isExternal: false
  href: System.Boolean.yml
  name: Boolean
  fullName: System.Boolean
- uid: System.Xml.ConformanceLevel
  parent: System.Xml
  isExternal: false
  href: System.Xml.ConformanceLevel.yml
  name: ConformanceLevel
  fullName: System.Xml.ConformanceLevel
- uid: System.Text.Encoding
  parent: System.Text
  isExternal: false
  href: System.Text.Encoding.yml
  name: Text.Encoding
  fullName: System.Text.Encoding
- uid: System.Text
  isExternal: false
  name: System.Text
  fullName: System.Text
- uid: System.String
  parent: System
  isExternal: false
  href: System.String.yml
  name: String
  fullName: System.String
- uid: System.Xml.NamespaceHandling
  parent: System.Xml
  isExternal: false
  href: System.Xml.NamespaceHandling.yml
  name: NamespaceHandling
  fullName: System.Xml.NamespaceHandling
- uid: System.Xml.NewLineHandling
  parent: System.Xml
  isExternal: false
  href: System.Xml.NewLineHandling.yml
  name: NewLineHandling
  fullName: System.Xml.NewLineHandling
- uid: System.Xml.XmlWriterSettings
  parent: System.Xml
  isExternal: false
  href: System.Xml.XmlWriterSettings.yml
  name: XmlWriterSettings
  fullName: System.Xml.XmlWriterSettings
- uid: System.ArgumentNullException
  isExternal: false
  href: System.ArgumentNullException.yml
  name: ArgumentNullException
  fullName: System.ArgumentNullException
  summary: The exception that is thrown when a null reference (Nothing in Visual Basic) is passed to a method that does not accept it as a valid argument.
