items:
- uid: System.Data.SqlClient.ApplicationIntent
  id: ApplicationIntent
  parent: System.Data.SqlClient
  children:
  - System.Data.SqlClient.ApplicationIntent.ReadOnly
  - System.Data.SqlClient.ApplicationIntent.ReadWrite
  href: System.Data.SqlClient.ApplicationIntent.yml
  name: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
  type: Enum
  source:
    remote: &o0
      path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
      branch: master
      repo: https://vicancy@github.com/dotnet/corefx.git
    path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
    startLine: 205
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: Specifies a value for @'System.Data.SqlClient.SqlConnectionStringBuilder.ApplicationIntent'. Possible values are ReadWrite and ReadOnly.
  syntax:
    content: public enum ApplicationIntent
    content.vb: Public Enum ApplicationIntent
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  id: ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  href: System.Data.SqlClient.ApplicationIntent.yml
  name: ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
  type: Field
  source:
    remote: *o0
    path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
    startLine: 207
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: The application workload type when connecting to a server is read only.
  syntax:
    content: ReadOnly = 1
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  id: ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  href: System.Data.SqlClient.ApplicationIntent.yml
  name: ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
  type: Field
  source:
    remote: *o0
    path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
    startLine: 208
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: The application workload type when connecting to a server is read write.
  syntax:
    content: ReadWrite = 0
references:
- uid: System.Data.SqlClient
  isExternal: false
  name: System.Data.SqlClient
  fullName: System.Data.SqlClient
  type: Namespace
