items:
- uid: System.Security
  id: System.Security
  children:
  - System.Security.AllowPartiallyTrustedCallersAttribute
  - System.Security.SecurityCriticalAttribute
  - System.Security.SecurityException
  - System.Security.SecuritySafeCriticalAttribute
  - System.Security.SecurityTransparentAttribute
  - System.Security.VerificationException
  href: System.Security.yml
  name: System.Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      path: src/System.Runtime/ref/System.Runtime.cs
      branch: master
      repo: https://vicancy@github.com/dotnet/corefx.git
    path: src/System.Runtime/ref/System.Runtime.cs
    startLine: 3062
  assemblies:
  - System.Runtime
  summary: The @'System.Security' namespace provides the underlying structure of the common language runtime security system, including base classes for permissions.
references:
- uid: System.Security.AllowPartiallyTrustedCallersAttribute
  isExternal: false
  href: System.Security.AllowPartiallyTrustedCallersAttribute.yml
  name: AllowPartiallyTrustedCallersAttribute
  fullName: System.Security.AllowPartiallyTrustedCallersAttribute
  type: Class
- uid: System.Security.SecurityCriticalAttribute
  isExternal: false
  href: System.Security.SecurityCriticalAttribute.yml
  name: SecurityCriticalAttribute
  fullName: System.Security.SecurityCriticalAttribute
  type: Class
  summary: Specifies that code or an assembly performs security-critical operations.
- uid: System.Security.SecurityException
  isExternal: false
  href: System.Security.SecurityException.yml
  name: SecurityException
  fullName: System.Security.SecurityException
  type: Class
- uid: System.Security.SecuritySafeCriticalAttribute
  isExternal: false
  href: System.Security.SecuritySafeCriticalAttribute.yml
  name: SecuritySafeCriticalAttribute
  fullName: System.Security.SecuritySafeCriticalAttribute
  type: Class
- uid: System.Security.SecurityTransparentAttribute
  isExternal: false
  href: System.Security.SecurityTransparentAttribute.yml
  name: SecurityTransparentAttribute
  fullName: System.Security.SecurityTransparentAttribute
  type: Class
  summary: Specifies that an assembly cannot cause an elevation of privilege.
- uid: System.Security.VerificationException
  isExternal: false
  href: System.Security.VerificationException.yml
  name: VerificationException
  fullName: System.Security.VerificationException
  type: Class
