items:
- uid: System.Net.Security
  id: System.Net.Security
  children:
  - System.Net.Security.AuthenticatedStream
  - System.Net.Security.AuthenticationLevel
  - System.Net.Security.EncryptionPolicy
  - System.Net.Security.LocalCertificateSelectionCallback
  - System.Net.Security.NegotiateStream
  - System.Net.Security.ProtectionLevel
  - System.Net.Security.RemoteCertificateValidationCallback
  - System.Net.Security.SslPolicyErrors
  - System.Net.Security.SslStream
  href: System.Net.Security.yml
  name: System.Net.Security
  fullName: System.Net.Security
  type: Namespace
  source:
    remote:
      path: src/Common/src/Interop/Windows/sspicli/SecuritySafeHandles.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/Common/src/Interop/Windows/sspicli/SecuritySafeHandles.cs
    startLine: 10
  assemblies:
  - System.Net.Primitives
  summary: The @'System.Net.Security' namespace provides network streams for secure communications between hosts.
references:
- uid: System.Net.Security.AuthenticationLevel
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.AuthenticationLevel.yml
  name: AuthenticationLevel
  fullName: System.Net.Security.AuthenticationLevel
- uid: System.Net.Security.SslPolicyErrors
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.SslPolicyErrors.yml
  name: SslPolicyErrors
  fullName: System.Net.Security.SslPolicyErrors
- uid: System.Net.Security.AuthenticatedStream
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.AuthenticatedStream.yml
  name: AuthenticatedStream
  fullName: System.Net.Security.AuthenticatedStream
- uid: System.Net.Security.EncryptionPolicy
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.EncryptionPolicy.yml
  name: EncryptionPolicy
  fullName: System.Net.Security.EncryptionPolicy
- uid: System.Net.Security.LocalCertificateSelectionCallback
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.LocalCertificateSelectionCallback.yml
  name: LocalCertificateSelectionCallback
  fullName: System.Net.Security.LocalCertificateSelectionCallback
- uid: System.Net.Security.NegotiateStream
  isExternal: false
  href: System.Net.Security.NegotiateStream.yml
  name: NegotiateStream
  fullName: System.Net.Security.NegotiateStream
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.ProtectionLevel.yml
  name: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.Net.Security.RemoteCertificateValidationCallback
  parent: System.Net.Security
  isExternal: false
  href: System.Net.Security.RemoteCertificateValidationCallback.yml
  name: RemoteCertificateValidationCallback
  fullName: System.Net.Security.RemoteCertificateValidationCallback
- uid: System.Net.Security.SslStream
  isExternal: false
  href: System.Net.Security.SslStream.yml
  name: SslStream
  fullName: System.Net.Security.SslStream
- uid: System.Net.Security
  isExternal: false
  name: System.Net.Security
  fullName: System.Net.Security
