items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  id: ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  parent: System.Runtime.CompilerServices
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.IsCompleted
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  href: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.yml
  name: ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter
  name.vb: ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter
  type: Struct
  source:
    remote: &o0
      path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 468
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Provides an awaiter for an awaitable object(@'System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1').
  syntax:
    content: 'public struct ConfiguredTaskAwaiter : ICriticalNotifyCompletion, INotifyCompletion'
    content.vb: Public Structure ConfiguredTaskAwaiter Implements ICriticalNotifyCompletion, INotifyCompletion
  implements:
  - System.Runtime.CompilerServices.ICriticalNotifyCompletion
  - System.Runtime.CompilerServices.INotifyCompletion
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.IsCompleted
  id: IsCompleted
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  href: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.yml
  name: IsCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.IsCompleted
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter.IsCompleted
  type: Property
  source:
    remote: *o0
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 491
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Gets a value that specifies whether the task being awaited has been completed.
  syntax:
    content: public bool IsCompleted { get; }
    content.vb: Public ReadOnly Property IsCompleted As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: true if the task being awaited has been completed; otherwise, false.
  exceptions:
  - type: System.NullReferenceException
    description: The awaiter was not properly initialized.
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult
  id: GetResult
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  href: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.yml
  name: GetResult()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter.GetResult()
  type: Method
  source:
    remote: *o0
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 523
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Ends the await on the completed task.
  syntax:
    content: public TResult GetResult()
    content.vb: Public Function GetResult As TResult
    return:
      type: '{TResult}'
      description: The result of the completed task.
  exceptions:
  - type: System.NullReferenceException
    description: The awaiter was not properly initialized.
  - type: System.Threading.Tasks.TaskCanceledException
    description: The task was canceled.
  - type: System.Exception
    description: The task completed in a faulted state.
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  id: OnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  href: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.yml
  name: OnCompleted(Action)
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter.OnCompleted(System.Action)
  type: Method
  source:
    remote: *o0
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 501
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Schedules the continuation action for the task associated with this awaiter.
  syntax:
    content: public void OnCompleted(Action continuation)
    content.vb: Public Sub OnCompleted(continuation As Action)
    parameters:
    - id: continuation
      type: System.Action
      description: The action to invoke when the await operation completes.
  exceptions:
  - type: System.ArgumentNullException
    description: The *continuation* argument is null.
  - type: System.NullReferenceException
    description: The awaiter was not properly initialized.
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  id: UnsafeOnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  href: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.yml
  name: UnsafeOnCompleted(Action)
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  type: Method
  source:
    remote: *o0
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 512
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Schedules the continuation action for the task associated with this awaiter.
  syntax:
    content: public void UnsafeOnCompleted(Action continuation)
    content.vb: Public Sub UnsafeOnCompleted(continuation As Action)
    parameters:
    - id: continuation
      type: System.Action
      description: The action to invoke when the await operation completes.
  exceptions:
  - type: System.ArgumentNullException
    description: The *continuation* argument is null.
  - type: System.NullReferenceException
    description: The awaiter was not properly initialized.
references:
- uid: System.Runtime.CompilerServices
  isExternal: false
  name: System.Runtime.CompilerServices
  fullName: System.Runtime.CompilerServices
- uid: System.Boolean
  parent: System
  isExternal: false
  href: System.Boolean.yml
  name: Boolean
  fullName: System.Boolean
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: '{TResult}'
  isExternal: false
  name: TResult
  fullName: TResult
- uid: System.Action
  isExternal: false
  href: System.Action.yml
  name: Action
  fullName: System.Action
- uid: System.NullReferenceException
  isExternal: false
  href: System.NullReferenceException.yml
  name: NullReferenceException
  fullName: System.NullReferenceException
  summary: The exception that is thrown when there is an attempt to dereference a null object reference.
- uid: System.Threading.Tasks.TaskCanceledException
  isExternal: false
  href: System.Threading.Tasks.TaskCanceledException.yml
  name: TaskCanceledException
  fullName: System.Threading.Tasks.TaskCanceledException
  summary: Represents an exception used to communicate task cancellation.
- uid: System.Exception
  parent: System
  isExternal: false
  href: System.Exception.yml
  name: Exception
  fullName: System.Exception
  summary: Represents errors that occur during application execution.To browse the .NET Framework source code for this type, see the Reference Source.
- uid: System.ArgumentNullException
  isExternal: false
  href: System.ArgumentNullException.yml
  name: ArgumentNullException
  fullName: System.ArgumentNullException
  summary: The exception that is thrown when a null reference (Nothing in Visual Basic) is passed to a method that does not accept it as a valid argument.
